linters:
    BorderZero:
        enabled: false

    CapitalizationInSelector:
        enabled: true
        ignored_names:
            - 'mCS-minimal-dark'

    ColorKeyword:
        enabled: true

    Comment:
        enabled: true

    DebugStatement:
        enabled: true

    DeclarationOrder:
        enabled: false

    DuplicateProperty:
        enabled: true

    ElsePlacement:
        enabled: true
        style: same_line # or 'new_line'

    EmptyLineBetweenBlocks:
        enabled: false
        ignore_single_line_blocks: true

    EmptyRule:
        enabled: true

    FinalNewline:
        enabled: false
        present: false

    HexLength:
        enabled: true
        style: short # or 'long'

    HexNotation:
        enabled: true
        style: lowercase # or 'uppercase'

    HexValidation:
        enabled: true

    IdWithExtraneousSelector:
        enabled: true

    Indentation:
        enabled: true
        width: 4

    LeadingZero:
        enabled: false
        style: exclude_zero # or 'include_zero'

    MergeableSelector:
        enabled: true
        force_nesting: true

    NameFormat:
        enabled: true
        convention: hyphenated_lowercase # or 'BEM', or a regex pattern

    PlaceholderInExtend:
        enabled: true

    PropertySortOrder:
        enabled: false

    PropertySpelling:
        enabled: true
        extra_properties: []

    QualifyingElement:
        enabled: true
        allow_element_with_attribute: true
        exclude:
            - 'app/styles/components/buttons.scss'
            - 'app/styles/layout/forms.scss'
            - 'app/styles/components/markdown-help.scss'

    SelectorDepth:
        enabled: true
        max_depth: 5

    Shorthand:
        enabled: false

    SingleLinePerSelector:
        enabled: true

    SpaceAfterComma:
        enabled: true

    SpaceAfterPropertyColon:
        enabled: true
        style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

    SpaceAfterPropertyName:
        enabled: true

    SpaceBeforeBrace:
        enabled: false
        allow_single_line_padding: false

    SpaceBetweenParens:
        enabled: true
        spaces: 0

    StringQuotes:
        enabled: true
        style: single_quotes # or double_quotes

    TrailingSemicolonAfterPropertyValue:
        enabled: true

    UnnecessaryMantissa:
        enabled: true

    UrlFormat:
        enabled: true

    UrlQuotes:
        enabled: true

    ZeroUnit:
        enabled: false

    ZeroUnits:
        enable: false

    NestingDepth:
        enabled: false
        max_depth: 4

    Compass::*:
        enabled: false

    ColorVariable:
        enabled: false

    PseudoElement:
        enabled: false

    ImportantRule:
        enable: false
